### ISSUE TITLE
improve user experience when beginning mentorship session (when the matching process is happening and when it begins)

### ISSUE THREAD

**Issue by ownzandy** [hack-duke/hackduke-mentorship-bot#5]
elaborate on what to do after being assigned a mentor (mentorbot should tell the participant to go to the private channel to talk to the mentor)
does a notification pop up when a person is invited to a new group?
if the mentor-participant pair has already been created before, will there be a notification still and what's the best way to make sure the participant and mentors go the correct channel

**Comment by Briguy52** [comment]
# Todos
- [x] Give background info on mentor and mentee (e.g. `<Mentee> would like help building a <insert app idea here>. <Mentor> has a background working with <insert skills here>`)
- [ ] Alert that the help session will last for 30 minutes
- [ ] Link to new channel from mentorbot DM  (trying to use `<#channelId|text>` format, but it's not working- probably should contact them and ask.

## Before match
- [ ] Welcome description (e.g. Hi, I'm the HackDuke mentor bot. If you say any of these commands, I'll do my best to match you with a mentor!)
- [ ] Possible commands (e.g. help web, help ios, help android, help getting started)
- [ ] Mentor bot should give a link to the newly created chat (regardless of the name)
- [ ] Do some push notification as well
- [ ] What to do about duplicate pairings?

## After match
- [ ] Give background info on mentor and mentee (e.g. `<Mentee> would like help building a <insert app idea here>. <Mentor> has a background working with <insert skills here>`)
- [ ] Alert that the help session will last for 30 minutes
- [ ] Prompt with any further commands
